-- DEBUGGING SCRIPT
-- 1. Create a log table to capture the error
CREATE TABLE IF NOT EXISTS public.auth_debug_logs (
  id bigint generated by default as identity primary key,
  user_id uuid,
  error_message text,
  error_code text,
  created_at timestamp with time zone default now()
);

-- Enable access
ALTER TABLE public.auth_debug_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read" ON public.auth_debug_logs FOR SELECT USING (true);
CREATE POLICY "System insert" ON public.auth_debug_logs FOR INSERT WITH CHECK (true);

-- 2. Update the Trigger to CATCH errors instead of failing
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
DECLARE
  default_username text;
  fullname text;
  avatar text;
BEGIN
  -- Generate safe username
  default_username := 'user' || LOWER(SUBSTRING(new.id::text FROM 1 FOR 8));
  
  -- Extract metadata
  fullname := COALESCE(new.raw_user_meta_data->>'full_name', 'Mortal User');
  avatar := COALESCE(new.raw_user_meta_data->>'avatar_url', '');

  BEGIN
    -- Try the insert
    INSERT INTO public.app_profiles_v2 (
      id, 
      username, 
      full_name, 
      avatar_url, 
      is_private, 
      is_verified_human,
      level, 
      xp
    )
    VALUES (
      new.id, 
      default_username, 
      fullname, 
      avatar, 
      false, 
      true,
      1,
      0
    );
  EXCEPTION WHEN OTHERS THEN
    -- If it fails, LOG IT and ALLOW the user creation to proceed
    INSERT INTO public.auth_debug_logs (user_id, error_message, error_code)
    VALUES (new.id, SQLERRM, SQLSTATE);
  END;

  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
