-- Social Features Schema

-- 1. Posts Table
create table if not exists public.app_posts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.app_profiles_v2(id) on delete cascade not null,
  image_url text not null,
  caption text,
  location_name text,
  location_lat double precision,
  location_lng double precision,
  is_hidden boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Likes Table
create table if not exists public.app_likes (
  id bigint generated by default as identity primary key,
  post_id bigint references public.app_posts(id) on delete cascade not null,
  user_id uuid references public.app_profiles_v2(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(post_id, user_id)
);

-- 3. Comments Table
create table if not exists public.app_comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.app_posts(id) on delete cascade not null,
  user_id uuid references public.app_profiles_v2(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Storage Bucket for Social Media
-- Note: You might need to create the 'social_media' bucket manually in the Supabase Dashboard if this fails.
insert into storage.buckets (id, name, public)
values ('social_media', 'social_media', true)
on conflict (id) do nothing;

-- RLS Policies

-- Posts
alter table public.app_posts enable row level security;

create policy "Posts are viewable by everyone" 
  on public.app_posts for select 
  using (true);

create policy "Users can create posts" 
  on public.app_posts for insert 
  with check ( auth.uid()::uuid = user_id );

create policy "Users can delete own posts" 
  on public.app_posts for delete 
  using ( auth.uid()::uuid = user_id );

create policy "Users can update own posts" 
  on public.app_posts for update 
  using ( auth.uid()::uuid = user_id );

-- Likes
alter table public.app_likes enable row level security;

create policy "Likes are viewable by everyone" 
  on public.app_likes for select 
  using (true);

create policy "Users can insert likes" 
  on public.app_likes for insert 
  with check ( auth.uid()::uuid = user_id );

create policy "Users can delete own likes" 
  on public.app_likes for delete 
  using ( auth.uid()::uuid = user_id );

-- Comments
alter table public.app_comments enable row level security;

create policy "Comments are viewable by everyone" 
  on public.app_comments for select 
  using (true);

create policy "Users can insert comments" 
  on public.app_comments for insert 
  with check ( auth.uid()::uuid = user_id );

create policy "Users can delete own comments" 
  on public.app_comments for delete 
  using ( auth.uid()::uuid = user_id );

-- Storage Policies (social_media bucket)
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'social_media' );

create policy "Authenticated users can upload"
  on storage.objects for insert
  with check ( bucket_id = 'social_media' and auth.role() = 'authenticated' );

create policy "Users can update own objects"
  on storage.objects for update
  using ( bucket_id = 'social_media' and auth.uid() = owner );

create policy "Users can delete own objects"
  on storage.objects for delete
  using ( bucket_id = 'social_media' and auth.uid() = owner );
